# Generated by Django 4.2.20 on 2025-05-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
